
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopily-Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href='/assets/imgs/shopping-cart.png' rel="icon" />
      <body className="bg-bodybg">
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
